apiVersion: v1
kind: Secret
metadata:
  name: bank-core-secret
  namespace: bank-account
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: bank_account
  SPRING_DATASOURCE_PASSWORD: bank_account
